import "./search.js";
import "./badges.js";
import "./fadeIn.js";
import "./swiper.js";
import "./promotion.js";
import "./floating.js";
import "./scrollMagic.js";
import "./thisYear.js";
import "./toTop.js";
